###
# Builder container
###
FROM golang:alpine AS builder

ENV CGOENABLED=1

WORKDIR /home/pufferpanel/build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -v -buildvcs=false -tags allowfsset -o /home/pufferpanel/curseforgetester github.com/pufferpanel/pufferpanel/v3/tools/curseforge

# Final image
FROM eclipse-temurin:21-alpine
WORKDIR /home/pufferpanel
ENV CURSEFORGE_KEY=""
ENV PUFFER_DAEMON_DATA_CACHE="/cache"

COPY --from=builder /home/pufferpanel/curseforgetester .


ENTRYPOINT ["./curseforgetester"]
CMD []